### ISSUE TITLE
Warning: /redaxo/index.php?page=multiglossar/settings

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/multiglossar#18]
`Warning: in_array() expects parameter 2 to be array, null given in /Users/abc/Sites/rex56/redaxo/src/addons/multiglossar/pages/settings.php on line 194`

Frische Installation.
REDAXO 5.6.4
PHP 7.1.19

**Comment by TobiasKrais** [comment]
Duplikat von https://github.com/FriendsOfREDAXO/multiglossar/issues/24
