### ISSUE TITLE
rex_addon::exists('yrewrite') Vs isAvailable

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/multiglossar#23]
Es gibt einige rex_addon::exists('yrewrite') checks im addon.
Ob ein addon existiert (vorhanden ist) oder ob dieses auch verfügbar ist, sind aber unterschiedliche Dinge... vermutlich müssten diese stellen angepasst werden?

**Comment by TobiasKrais** [comment]
Ist behoben.
