### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by webregie** [FriendsOfREDAXO/multiglossar#24]
Hab es in einem Redaxo mit Multidomain installiert. Unter Konfiguration kommt 9x 

Warning: in_array() expects parameter 2 to be array, null given in redaxo/src/addons/multiglossar/pages/settings.php on line 197

**Comment by TobiasKrais** [comment]
Kann jemand den PR testen: https://github.com/FriendsOfREDAXO/multiglossar/pull/32. Ich nutze kein Multiglossar.

**Comment by f5alex** [comment]
Keine Warnings unter 
REDAXO | 5.13.3
PHP | 7.3.31
(höher kann ich derzeit noch nicht gehen)

**Comment by TobiasKrais** [comment]
Dann marge ich den mal un schließe den Issue. Danke dir!
