### ISSUE TITLE
noch aktuell?

### ISSUE THREAD

**Issue by abra100pro** [FriendsOfREDAXO/multiglossar#33]
Hallo, Beta aus dem Jahr 2017 – ist das Add-on noch aktuell?
Wäre eine Supersache.

**Comment by TobiasKrais** [comment]
Wir haben heute ein paar Änderungen gemacht und Issues geschlossen. Kannst du eventuell die aktuelle Git Version testen und eventuell auch diesen PR: https://github.com/FriendsOfREDAXO/multiglossar/pull/32

Ich denke dann könnten wir ein Release machen.
