### ISSUE TITLE
Speichern von Begriffen nicht möglich

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/multiglossar#35]
Problem:

`"error" => "Column 'casesensitive' cannot be null"`

Lösung:

https://github.com/FriendsOfREDAXO/multiglossar/blob/master/pages/main.php#L117
hier statt false hinten einfach true

Danke an Thorben

**Comment by TobiasKrais** [comment]
https://github.com/FriendsOfREDAXO/multiglossar/commit/973b869b17caae31e985358318849fd10cf0b193
