### ISSUE TITLE
Beispielinhalte

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/multiglossar#7]
Vielleicht besteht mal die Möglichkeit einige Beispielinhalte bereitzustellen. (Importlink änglich wie bei den Aufgaben?).

Die Kür wären **richtige** Inhalte. Thema IT, Webentwicklung, REDAXO?

So kannman sich direkt an die Entwicklung von Ausgabemodulen machen :-))

LG
Oliver

**Comment by skerbis** [comment]
Bin eher Fan einer leeren Lösung zur direkten Einpflege.

**Comment by olien** [comment]
Ich bin auch kein Fan von ich muß erst 600 Datensätze löschen.
Aber für die Entwicklung werden nunmal Daten benötigt. Die sollen ja nicht gleich importiert werden...

**Comment by skerbis** [comment]
Ich sag ja in eine REDAXO - Demo packen

**Comment by olien** [comment]
Ich finde die gehören zum AddOn...

**Comment by skerbis** [comment]
@dtpop was meinst du?

**Comment by schuer** [comment]
Falls ihr Screenshots wollt, benötigen wir sowieso ein paar Beispieldaten ;)

**Comment by skerbis** [comment]
Wer will schreiben?

**Comment by skerbis** [comment]
Anscheinend will niemand? @schuer @olien @crydotsnake vielleicht?

**Comment by skerbis** [comment]
@crydotsnake Demo Glossar-Einträge
Nicht Artikel ;-)

**Comment by crydotsnake** [comment]
@skerbis Aber diese kann man bei Begriffe eintragen, richtig?.

**Comment by skerbis** [comment]
Ja

**Comment by crydotsnake** [comment]
Geht es nur Darum Beispiel Glossar-Einträge anzulegen?

**Comment by skerbis** [comment]
Korrekt

**Comment by schuer** [comment]
5 Jahre später: Ich denke, wir sollten hier mal schließen.
Falls jemand aber weiterhin Bedarf sieht, gerne wieder öffnen!
